# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dyname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prefix', models.CharField(max_length=50, verbose_name='domain prefix')),
                ('curr_ip', models.GenericIPAddressField(verbose_name='current ip')),
                ('mod_date', models.DateField(auto_now=True, verbose_name='last modified')),
            ],
        ),
    ]
