# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 19:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddns_query', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dyname',
            old_name='curr_ip',
            new_name='ip',
        ),
        migrations.RemoveField(
            model_name='dyname',
            name='mod_date',
        ),
        migrations.AddField(
            model_name='dyname',
            name='mod',
            field=models.DateTimeField(auto_now=True, verbose_name='last modified'),
        ),
    ]
