# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-07 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddns_query', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyname',
            name='ip',
            field=models.GenericIPAddressField(default='0.0.0.0', verbose_name='current ip'),
        ),
        migrations.AlterField(
            model_name='dyname',
            name='primary_dns_host',
            field=models.CharField(default='ns1.aszabados.eu', max_length=200, verbose_name='Primary DNS server hostname'),
        ),
        migrations.AlterField(
            model_name='dyname',
            name='zone',
            field=models.CharField(default='ddns.aszabados.eu', max_length=200, verbose_name='DNS zone'),
        ),
    ]
