# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-12 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ddns_query', '0003_auto_20170312_1932'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dyname',
            name='prefix',
            field=models.CharField(max_length=15, unique=True, verbose_name='domain prefix'),
        ),
    ]
